apiVersion: v1
kind: Secret
metadata:
  name: echo-api-db-secret
data:
  dbpass: UEBzc3cwcmQ=
  connString: U2VydmVyPWVjaG8tZGItc3ZjLDE0MzM7SW5pdGlhbCBDYXRhbG9nPWVjaG8tbG9nO1VzZXIgSUQ9U0E7UGFzc3dvcmQ9UEBzc3cwcmQ7