version: '3'
services:
  azure-vote-back:
    image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-front:
    image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
    environment:
      REDIS: azure-vote-back
    ports:
        - "8080:80"