apiVersion: v1
kind: Pod
metadata:
  name: vote-app
spec:
  containers:
    - name: azure-vote-back
      image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
      ports:
        - containerPort: 6379
      env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
      resources:
        limits:
          cpu: "1"
          memory: "1G"
        requests:
          cpu: "0.5"
          memory: "500M"
    - name: azure-vote-front
      image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
      ports:
        - containerPort: 80
      env:
        - name: REDIS
          value: localhost
      resources:
        limits:
          cpu: "1"
          memory: "1G"
        requests:
          cpu: "0.5"
          memory: "500M"