version: '3'
services:
  echo-webapp:
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - EchoAPIServer=echo-api

  echo-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
        - "9000:80"
    volumes:
      - ./.vsdbg:/remote_debugger:rw

    