apiVersion: v1
kind: Pod
metadata:
  name: vote-app
spec:
  containers:
    - name: vote-back
      image: ghcr.io/theonorg/vote-app:redis-arm
      ports:
        - containerPort: 6379
      env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
    - name: vote-front
      image: ghcr.io/theonorg/vote-app:python-redis-arm
      ports:
        - containerPort: 80
      env:
        - name: REDIS
          value: localhost