apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  database: mongodb
  database_uri: mongodb://localhost:27017

  user-interface.properties: |
    color.good=green
    color.bad=yellow
    allow.textmode=true