apiVersion: v1
kind: Pod
metadata:
  name: no-resources-pod
spec:
  containers:
  - name: no-resources
    image: nginx
    resources:
      limits:
        cpu: 20000m
      requests:
        cpu: 20000m