apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workload-1
  template:
    metadata:
      labels:
        app: workload-1
        color: maroon
    spec:
      containers:
        - name: workload
          image: nginx:1.18
          ports:
            - containerPort: 80
