apiVersion: apps/v1
kind: Deployment
metadata:
  name: otherdep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otherdep
  template:
    metadata:
      labels:
        app: otherdep
        color: red
    spec:
      containers:
      - name: otherdep
        image: nginx:1.18
        ports:
        - containerPort: 80               
