apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: new-ns
spec:
  containers:
  - image: nginx:1.18-alpine
    name: nginx-container
    resources: {}
    ports:
    - containerPort: 80
