apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: file-secret
data:
  secret-file.json: ew0KICAgICJ1c2VyIjogIm15dXNlciIsDQogICAgInRva2VuIjogIm15dG9rZW4iLA0KICAgICJ1cmwiOiAiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS8iDQp9